# Generated by Django 5.0.6 on 2024-07-15 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_eventuser_groups_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Registration',
            new_name='AttendeeRegistration',
        ),
    ]
